language: generic
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.cache
    - $HOME/conda
# Install conda
before_install:
  - tests/install_conda.sh
  - export PATH=$HOME/conda/bin:$PATH
# Run test
script:
  - tests/test.sh
