language: generic
cache:
  directories:
    - /home/travis/.cache
    - /home/travis/conda
# Install conda
before_install:
  - tests/install_conda.sh
  - export PATH=$HOME/conda/bin:$PATH
# Run test
script:
  - tests/test.sh
