#!/usr/bin/env Rscript
#
# This file is part of TRUmiCount
#
# TRUmiCount is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TRUmiCount is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with TRUmiCount.  If not, see <http://www.gnu.org/licenses/>.

# ******************************************************************************
# *** Arguments Definition *****************************************************
# ******************************************************************************
VERSION <- "0.9.13"
DOCSTRING <- paste0('
Usage: trumicount (--input-bam INBAM | --input-umitools-group-out GROUPSINTAB | --input-umis UMISINTAB) [options] [--umitools-option UMITOOLSOPT]...

Version ', VERSION, ' Copyright 2017-2018 Florian G. Pflug

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

Options:
--input-bam FILE                read UMIs from FILE (uses `umi_tools group`)
--input-umitools-group-out FILE read UMIs from FILE produced by `umi_tools group`
--input-umis FILE               read UMIs from FILE (previously produced by --output-umis)
--output-counts FILE            write bias-corrected per-group counts and models to FILE
--output-umis FILE              write UMIs reported by `umi_tools group` to FILE
--output-final-umis FILE        write strand-combined and filtered UMIs to FILE
--output-readdist FILE          write global reads/UMI distribution (before and after filtering) to FILE
--output-plots PLOT             write diagnostic plots in PDF format to PLOT
--output-groupwise-fits FILE    write group-wise model details to FILE
--output-genewise-fits FILE     obsolete name for --output-groupwise-fits
--umitools UMITOOLS             use executable UMITOOLS to run `umi_tools group` [Default: umi_tools]
--umitools-option UMITOOLSOPT   pass UMITOOLSOPT to `umi_tools group` (see `umi_tools group --help`)
--umi-sep UMISEP                assume UMISEP separates read name and UMI (passed to umi_tools) [Default: _]
--umipair-sep UMIPAIRSEP        assume UMIPAIRSEP separates read1 and read2 UMI (see Strand UMIs) [Default: ]
--paired                        assume BAM file contains paired reads (passed to umi_tools) [Default: FALSE]
--mapping-quality MAPQ          ignored read with mapping quality below MAPQ (passed to umi_tools) [Default: 20]
--filter-strand-umis            filtes UMIs where only one strands was observed [Default: FALSE]
--combine-strand-umis           combine UMIs strand pairs (implies --filter-strand-umis) [Default: FALSE]
--threshold THRESHOLD           remove UMIs with fewer than THRESHOLD reads
--threshold-quantile Q          use quantile Q of the raw read-count distribution for THRESHOLD [Default: 0.2]
--molecules MOLECULES           assume UMIs are initially represented by MOLECULES copies (strands) [Default: 2]
--group-per KEY1,KEY2,...       counts UMIs per distinct key(s), can be "cell" and/or "gene",
                                "cell" implies --umitools-option --per-cell [Default: gene]
--skip-groupwise-fits           skip group-wise model fitting, stop after plotting the global fit
--include-filter-statistics     add filtered and unfiltered read and UMI counts to count table [Default: FALSE]
--groupwise-min-umis MINUMIS    use global estimates for groups with fewer than MINUMIS (strand) UMIs [Default: 5]
--genewise-min-umis MINUMIS     obsolete name for --groupwise-min-umis
--cores CORES                   spread group-wise model fitting over CORES cpus [Default: 1]
--variance-estimator VAREST     use VAREST to estimate variances, can be "lsq" or "mle" [Default: lsq]
--digits DIGITS                 number of digits to output [Default: 3]
--plot-hist-bin PLOTXBIN        make read count histogram bins PLOTXBIN wide
--plot-hist-xmax PLOTXMAX       limit read count histogram plot to at most PLOTXMAX reads per UMI
--plot-skip-phantoms            do not show phantom UMIs in histogram plot [Default: FALSE]
--plot-var-bins PLOTVARBINS     plot PLOTVARBINS separate emprirical variances [Default: 10]
--plot-var-logy                 use log scale for the variance (y) axis [Default: FALSE]
--verbose                       enable verbose output
')
OPTS.INVALID <- list(
  `input-bam`=c('input-umitools-group-out', 'input-umis'),
  `input-umitools-group-out`=c('input-bam', 'input-umis'),
  `input-umis`=c('input-bam', 'input-umitools-group-out')
)

# ******************************************************************************
# *** AWK Programm to post-process umi_tools output  ***************************
# ******************************************************************************
# The AWK program to transfrom the output of "umitools group" into a table of grouped UMIs
# We (crudely) remove newlines and comments, since we pass the program as a command-line
# argument to awk
GROUPOUT2UMIS.AWK <- gsub("\\s*(#.*)?\\n\\s*", "", perl=TRUE, '
BEGIN {
  gidp=-1;  # Prev. group id
  numis=1;  # Distinct # of raw UMIs
  lp="";    # Prev. line
  umip="";  # Prev. raw UMI
  FS="\\t";
  print "gene" "\\t" "cell" "\\t" "pos" "\\t" "end" "\\t" "umi" "\\t" "rawumis" "\\t" "reads";
}
NR==1 {
  # Locate columns
  Iread_id=Icell=Icontig=Iposition=Iposition2=Igene=Iumi=Iumi_count=Ifinal_umi=Ifinal_umi_count=Iunique_id=-1;
  for (i=1;i<=NF;i++) {
    switch ($i) {
      case "read_id": Iread_id=i; break;
      case "cell": Icell=i; break;
      case "contig": Icontig=i; break;
      case "position": Iposition=i; break;
      case "position2": Iposition2=i; break;
      case "gene": Igene=i; break;
      case "umi": Iumi=i; break;
      case "umi_count": Iumi_count=i; break;
      case "final_umi": Ifinal_umi=i; break;
      case "final_umi_count": Ifinal_umi_count=i; break;
      case "unique_id": Iunique_id=i; break;
    }
  }
}
NR>1 {
  # Store because $0 might be reset below
  l=$0;
  gid=$Iunique_id;
  umi=$Iumi;
  if (gidp==-1) {
    # First line, skip
  }
  else if (gid!=gidp) {
    # Group changed, output previous group
    $0=lp; # Switch back to (last line of) previous group
    print ($Igene=="NA"?$Icontig:$Igene) "\\t" (Icell>0?$Icell:"") "\\t" $Iposition "\\t" (Iposition2>0?$Iposition2:"NA") "\\t" $Ifinal_umi "\\t" numis "\\t" $Ifinal_umi_count;
    numis=1;
  }
  else if (umi!=umip) {
    # Raw UMI changed within group
    numis+=1;
  }
  # Remember prev. line, group id and UMI
  lp=l;
  gidp=gid;
  umip=umi
}
END {
  # Output last group
  $0=lp;
  print ($Igene=="NA"?$Icontig:$Igene) "\\t" (Icell>0?$Icell:"") "\\t" $Iposition "\\t" (Iposition2>0?$Iposition2:"NA") "\\t" $Ifinal_umi "\\t" numis "\\t" $Ifinal_umi_count;
}
')

# ******************************************************************************
# *** Utilities  ***************************************************************
# ******************************************************************************
GZEXT <- "\\.(gz|gzip2)$"
BZ2EXT <- "\\.(bz2|bzip2)$"

open_byext <- function(path, ...) {
  if (grepl(GZEXT, path))
    gzfile(path, ...)
  else if (grepl(BZ2EXT, path))
    bzfile(path, ...)
  else
    file(path, ...)
}

format_table <- function(t, ...) {
  for (n in names(t)) {
    if (is.numeric(t[[n]]))
      t[[n]] <- sapply(t[[n]], format, ...)
  }
  return(t)
}

# ******************************************************************************
# *** Parse arguments **********************************************************
# ******************************************************************************
ARGS <- docopt::docopt(DOCSTRING, strip_names=TRUE)
ARGS$`mapping-quality` <- as.integer(ARGS$`mapping-quality`)
if (ARGS$`mapping-quality` < 0)
  stop("Mapping quality threshold must be non-negative")
ARGS$`strand-umis` <- (ARGS$`filter-strand-umis` || ARGS$`combine-strand-umis`)
if (!is.null(ARGS$threshold)) {
	ARGS$threshold <- as.integer(ARGS$threshold)
  if (ARGS$threshold < 0)
    stop("The read-count threshold must be non-negative")
}
ARGS$threshold.quantile <- as.numeric(ARGS$`threshold-quantile`)
if ((ARGS$threshold.quantile < 0) || (ARGS$threshold.quantile >= 1))
  stop("Quantile for automatic threshold selection must lie within [0, 1)")
ARGS$molecules <- as.integer(ARGS$molecules)
ARGS$`group-per` <- strsplit(ARGS$`group-per`, split=",", fixed=TRUE)[[1]]
if (length(setdiff(ARGS$`group-per`, c("gene", "cell"))) > 0)
  stop("Group key must be a combination of 'gene' and 'cell'")
if (length(ARGS$`group-per`) == 0)
  stop("Group key cannot be empty")
ARGS$group.rhs.expr <- eval(parse(text=paste0("quote(", paste(ARGS$`group-per`, collapse=" + "), ")")))
ARGS$cores <- as.integer(ARGS$cores)
if (ARGS$cores < 0)
  stop("The number of cores must be non-negative")
ARGS$digits <- as.integer(ARGS$digits)
if (ARGS$digits < 0)
  stop("The number of digits must be non-negative")
if (!is.null(ARGS$`output-genewise-fits`))
  ARGS$`output-groupwise-fits` <- ARGS$`output-genewise-fits`
if (!is.null(ARGS$`genewise-min-umis`))
  ARGS$`groupwise-min-umis` <- ARGS$`genewise-min-umis`
ARGS$`plot-hist-bin` <- if (!is.null(ARGS$`plot-hist-bin`)) as.integer(ARGS$`plot-hist-bin`) else NULL
ARGS$`plot-hist-xmax` <- if (!is.null(ARGS$`plot-hist-xmax`)) as.numeric(ARGS$`plot-hist-xmax`) else NULL
ARGS$`plot-var-bins` <- if (!is.null(ARGS$`plot-var-bins`)) as.numeric(ARGS$`plot-var-bins`) else NULL
ARGS$`variance-estimator` <- match.arg(ARGS$`variance-estimator`, c('mle', 'lsq'))
ARGS$`var-est-distfree` <- (ARGS$`variance-estimator` == 'lsq')
if (ARGS$verbose)
  print(list(`Command Line Arguments`=ARGS))
if (ARGS$cores > 1) {
  message('*** Loading library `parallel` to allow computations on ', ARGS$cores, ' cores')
  library(parallel)
}

# Set options according to arguments
options(digits=ARGS$digits)

# ******************************************************************************
# *** Create connection to read grouped UMI table from *************************
# ******************************************************************************
umis_con <- if (!is.null(ARGS$`input-umis`)) {
  # Simple read grouped UMI table from file as-is
  if (sum(!sapply(ARGS[OPTS.INVALID$`input-umis`], is.null)) > 0)
    stop('--input-umis is incompatible with ', paste(OPTS.INVALID$`input-umis`, collapse=', '))

  # Table will be read from this file connection
  message('*** Reading UMI table from ', ARGS$`input-umis`)
  open_byext(ARGS$`input-umis`, open='r')
} else {
  # Grouped UMI table must be created
  cmds <- list()

  if (!is.null(ARGS$`input-bam`)) {
    # Input is BAM File, we use umi_tools to group similar UMIs. It outputs a line per read,
    # but indicates which reads belong to the same UMI group.
    message('*** Will use ', ARGS$`umitools`,' to extract UMIs from ', ARGS$`input-bam`)
    cmds[[length(cmds)+1]] <- paste(shQuote(ARGS$`umitools`), 'group', '--group-out /dev/stdout',
                                    '-I', shQuote(ARGS$`input-bam`),
                                    ifelse(ARGS$verbose, '--log2stderr', '-L /dev/null'),
                                    '--umi-sep', shQuote(ARGS$`umi-sep`),
                                    ifelse("cell" %in% ARGS$`group-per`, '--per-cell', ''),
                                    ifelse(ARGS$paired, '--paired', ''),
                                    '--mapping-quality', ARGS$`mapping-quality`,
                                    paste(shQuote(ARGS$`umitools-option`), collapse=' '), sep=' ')
  }
  else if (!is.null(ARGS$`input-umitools-group-out`)) {
    # Input is the raw 'umitools group' output. 
    if (sum(!sapply(ARGS[OPTS.INVALID$`input-umitools-group-out`], is.null)) > 0)
      stop('--input-umitools-group-out is incompatible with ', paste(OPTS.INVALID$`input-umitools-group-out`, collapse=', '))
    tool <- if (grepl(GZEXT, ARGS$`input-umitools-group-out`)) 'zcat'
    else if (grepl(BZ2EXT, ARGS$`input-umitools-group-out`)) 'bzcat'
    else 'cat'
    message('*** Will read `umi_tools --group` output from ', ARGS$`input-umitools-group-out`)
    cmds[[length(cmds)+1]] <- paste(tool, shQuote(ARGS$`input-umitools-group-out`), sep=' ')
  }

  # Reduce 'umitools group' output to a single line per group. 
  cmds[[length(cmds)+1]] <- paste('gawk', shQuote(GROUPOUT2UMIS.AWK), sep=' ')

  # If requested, save the grouped UMI table. The table can later be loaded directly
  # using --input-umis
  if (!is.null(ARGS$`output-umis`)) {
    # Materialize table, then read back
    tool <- if (grepl(GZEXT, ARGS$`output-umis`)) 'gzip --stdout'
    else if (grepl(BZ2EXT, ARGS$`output-umis`)) 'bzip2 --stdout'
    else 'cat'
    cmds[[length(cmds)+1]] <- paste(tool, '>', shQuote(ARGS$`output-umis`), sep=' ')
    message('*** Reading UMIs, writing UMI table to ', ARGS$`output-umis`)
    if (ARGS$verbose)
      cat(paste0('Command: ', paste(cmds, collapse=" |\n         "), "\n"))
    system(paste(cmds, collapse=' | '))

    # Table will be read from the created file
    open_byext(ARGS$`output-umis`, open='r')
  } else {
    # Table will be read from this pipe
    message('*** Reading UMIs')
    if (ARGS$verbose) {
      cat(paste0('Command: ', paste(cmds, collapse=" |\n         "), "\n"))
    }
    pipe(paste(cmds, collapse=' | '), open='r')
  }
}

# ******************************************************************************
# *** Read table using connection established above ****************************
# ******************************************************************************
library(data.table)
umis <- data.table(read.table(umis_con, header=TRUE, sep="\t",
                              colClasses=c(gene='factor', cell='factor',
                                           pos='numeric', end='numeric', umi='character',
                                           rawumis='numeric', 'reads'='numeric')))
close(umis_con)
message('Found ', nrow(umis), ' UMIs for ', length(levels(umis$gene)), ' genes in ',
        length(unique(umis$cell)), ' cells within ', sum(umis$reads), ' reads ',
        'after grouping of similar UMIs')

# ******************************************************************************
# *** Combine and/or filter UMI strand pairs stemming a single fragment ********
# ******************************************************************************
# In combine-strand mode, UMIs that correspond to the two strands of a single
# template molecule are joined together (this requires Y-shaped adapter which
# allow the PCR products of the two strands to be distinguished). Such pairs
# are recognized by their "reciprocity" -- first and second read of the mate
# pair are swapped, INCLUDING the UMIs found on these reads.
if (ARGS$`strand-umis`) {
  # Usually, molecules should be set to 1 since UMIs are initially represented by
  # only a single strand
  if (ARGS$molecules != 1)
    warning(paste0('Number of molecules is ', ARGS$molecules, ', yet for ',
                   '--filter-strand-umis and --combine-strand-umis setting ',
                   '--molecules 1 is usually correct'))
  umis.m <- if (ARGS$`umipair-sep` != '') {
    # Split at specified umi pair separator
    umis[,list(gene, cell, pos=end, end=pos,
               umi=as.character(unlist(lapply(FUN=function(e) {paste(rev(e), collapse=ARGS$`umipair-sep`)},
                                              strsplit(umi, ARGS$`umipair-sep`, fixed=TRUE)))),
               reads=reads) ]
  } else {
    # Split in the middle
    if (any(nchar(umis$umi) %% 2 != 0))
      stop('If no umi pair separator is specified, umis are split in the middle and must have even length')
    umis[,list(gene, cell, pos=end, end=pos,
               umi=paste0(substr(umi, nchar(umi)/2+1, nchar(umi)), substr(umi, 1, nchar(umi)/2)),
               reads=reads) ]
  }
}
if (ARGS$`combine-strand-umis`) {
  # For each reciprocal UMI pair, we keep only the one where the first read
  # maps in forward direction, and (arbitrarily?) call it the one mapping to
  # the plus strand. We keep the strand-specific read counts in two columns,
  # reads.plus and reads.minus, and set the overall read count to the sum of
  # the two.
  message('*** Merging UMIs belonging to the two strands of a single template molecule')
  umis <- umis[pos < end]
  umis[, reads.plus := reads ]
  umis[, reads.minus := umis.m[umis, reads, on=c("gene", "cell", "pos", "end", "umi")] ]
  umis[, reads := NULL ]
  umis <- umis[is.finite(reads.plus) & is.finite(reads.minus)]
  # Use reads.plus and reads.minus as separate (independent) read counts
  reads.expr <- expression(c(reads.plus, reads.minus))
  group.expr <- eval(substitute(c(reads.plus,reads.minus) ~ rhs, list(rhs=ARGS$group.rhs.expr)))
} else if (ARGS$`filter-strand-umis`) {
  # We remove UMIs that are not part of a reciprocal pair, but keep the
  # constituing UMIs of each pair as separate UMIs (unlike combine-strand-umis)
  message('*** Filtering UMIs whose reciproal UMI belong to the other strand is missing')
  umis[, reads.other := umis.m[umis, reads, on=c("gene", "cell", "pos", "end", "umi")] ]
  umis <- umis[is.finite(reads) & is.finite(reads.other)]
  # Simply use "reads" columns as read counts
  reads.expr <- expression(reads)
  group.expr <- eval(substitute(reads ~ rhs, list(rhs=ARGS$group.rhs.expr)))
} else {
  # Simply use "reads" columns as read counts
  reads.expr <- expression(reads)
  group.expr <- eval(substitute(reads ~ rhs, list(rhs=ARGS$group.rhs.expr)))
}
message("*** Counting & correcting the number of UMIs per ", paste(ARGS$`group-per`, collapse=" and "))

# ******************************************************************************
# *** Automatically set a (somewhat) sensible threshold if noen was supplied ***
# ******************************************************************************
if (is.null(ARGS$threshold)) {
  counts <- if (ARGS$`combine-strand-umis`)
    umis[, c(reads.plus, reads.minus)]
  else
    umis[, reads]
  ARGS$threshold <- floor(quantile(counts, ARGS$threshold.quantile,
                                   na.rm=TRUE, type=2))
  threshold.qact <- sum(counts < ARGS$threshold) / length(counts)
  message('*** Autoselected threshold ', ARGS$threshold , ' reads/UMI such that ',
          round(100*threshold.qact), '% (<= ',
          round(100*ARGS$threshold.quantile), '%', ') of UMIs are filtered out')
}

# ******************************************************************************
# *** Filter with read-count threshold *****************************************
# ******************************************************************************
# When applying the threshold, we filter based on the strand--specific counts, and
# require BOTH to be sufficiencly large.
umis.prefilter <- umis
if (ARGS$threshold > 0) {
  message('*** Filtering out UMIs with fewer than ', ARGS$threshold, ' reads ',
          'as putative phantoms')
  umis <- if (ARGS$`combine-strand-umis`)
    umis[(reads.plus >= ARGS$threshold) & (reads.minus >= ARGS$threshold)]
  else
    umis[reads >= ARGS$threshold]
}

# ******************************************************************************
# *** Determine per-UMI read counts ********************************************
# ******************************************************************************
readcounts <- umis[, eval(reads.expr)]
readcounts.prefilter <- umis.prefilter[, eval(reads.expr)]

# ******************************************************************************
# *** Output final UMI table ***************************************************
# ******************************************************************************
if (!is.null(ARGS$`output-final-umis`)) {
  f <- open_byext(ARGS$`output-final-umis`, open='w')
  write.table(umis, file=f,
              col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
  close(f)
}

# ******************************************************************************
# *** Output global reads/UMI distribution *************************************
# ******************************************************************************
if (!is.null(ARGS$`output-readdist`)) {
  readdist <- data.table(readcount=0:max(readcounts, readcounts.prefilter),
                         n.umis.prefilter=0,
                         n.umis=0)
  set_numis <- function(col, rc) {
    r <- rle(sort(rc))
    readdist[[col]][match(r$values, readdist$readcount)] <<- r$lengths
  }
  set_numis('n.umis.prefilter', readcounts.prefilter)
  set_numis('n.umis', readcounts)
  f <- open_byext(ARGS$`output-readdist`, open='w')
  write.table(readdist, file=f,
              col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
  close(f)
}

# ******************************************************************************
# *** Report final UMI count ***************************************************
# ******************************************************************************
message(nrow(umis), ' UMIs remained for ', length(levels(umis$gene)), ' genes in ',
        length(unique(umis$cell)), ' cells within ', sum(umis$reads), ' reads ',
        'after applying filters')
if (nrow(umis) < 2)
  stop("Too few UMIs to continue")

# ******************************************************************************
# *** Determine expression for the loss ****************************************
# ******************************************************************************
# Usually, this is simply "p0", i.e. the probability of an UMI having fewer than
# T (threshold) reads. But when we're dealing with stranded UMIs, an UMI is
# filtered out if *either* one of the two reciprocal mates have fewer than T
# reads (in combine-strand-umis mode), or if the UMI has fewer than T reads and
# the mate has zero reads (in filter-strand-umis mode).
loss.expr <- if (ARGS$`combine-strand-umis`) {
  # We filter UMIs which either have fewer than T reads, or whose reciprocal
  # mate has fewer than T reads
  expression(1 - (1 - p0)^2)
} else if (ARGS$`filter-strand-umis`) {
  # We filter UMIs whose reciprocal mate wasn't detected (0 reads), or
  # which have fewer than T reads.
  expression(1 - (1 - p0) * (1 - dgwpcrpois(0, threshold=0, molecules=ARGS$molecules,
                                            efficiency=efficiency, lambda0=lambda0)))
} else
  # Each UMI is treated individually, the loss is simply p0
  expression(p0)

# ******************************************************************************
# *** Fit global model *********************************************************
# ******************************************************************************
message('*** Fitting global PCR and sequencing model')
library(gwpcR)
gm <- tryCatch({
  gwpcrpois.est(umis[, eval(reads.expr)], method="mom", loss=loss.expr,
               threshold=ARGS$threshold, molecules=ARGS$molecules,
               ctrl=list(maxit=2000))
}, error=function(e) {
  message('ERROR: Failed to estimate global model parameters!')
  NULL
})
if (!is.null(gm)) {
  message('Overall efficiency ', round(100*gm$efficiency), '%, depth ',
          round(gm$lambda0, digits=2), ' reads/UMI, loss ', round(100*gm$loss), '%')
}

# ******************************************************************************
# *** Open Plot Output PDF File ************************************************
# ******************************************************************************
if (!is.null(ARGS$`output-plots`)) {
  message('*** Opening PDF ', ARGS$`output-plots`, ' for plot output')
  pdf(file=ARGS$`output-plots`, onefile=TRUE, height=3.5, width=8)
  pdf.close <- function(e) {
    message('*** Finishing PDF ', ARGS$`output-plots`)
    dev.off()
  }
  environment(pdf.close) <- list2env(list(ARGS=ARGS, dev.off=dev.off),
                                     parent=baseenv())
  pdf.guard <- new.env(parent=emptyenv())
  invisible(reg.finalizer(pdf.guard, pdf.close, onexit=TRUE))
}

# ******************************************************************************
# *** Plot global reads/UMI distribution ***************************************
# ******************************************************************************
if (!is.null(ARGS$`output-plots`)) {
  message('*** Plotting reads/UMI distribution')
  x.bin <- ifelse(!is.null(ARGS$`plot-hist-bin`),
                  ARGS$`plot-hist-bin`,
                  max(1, floor(max(readcounts) / nclass.Sturges(readcounts))))
  h.breaks <- seq(from=0,
                  to=x.bin*ceiling(max(readcounts)/x.bin),
                  by=x.bin)
  x.max <- ifelse(!is.null(ARGS$`plot-hist-xmax`),
                  ARGS$`plot-hist-xmax`,
                  max(h.breaks))
  # Histograms
  h <- hist(readcounts, breaks=h.breaks, right = FALSE, plot=FALSE)
  h.pf <- hist(readcounts.prefilter, breaks=h.breaks, right = FALSE, plot=FALSE)
  # Determine y range, ensure max. is nicely printable
  y.max <- max((if (!ARGS$`plot-skip-phantoms`) h.pf else h)$counts)
  y.max <- if ((y.max.nice <- signif(y.max, digits=2)) >= y.max)
    y.max.nice
  else
    signif(y.max*1.1, digits=2)
  # Setup plotting
  par(mar=c(5.1, 3.1, 1.1, 2.5/par("csi")), cex.axis=0.8)
  plot.new()
  plot.window(xlim=c(0, x.max), ylim=c(0, y.max), yaxt="n", xlab="", ylab="", main="")
  # Compute y range
  # Plot phantoms if requested
  if (!ARGS$`plot-skip-phantoms`)
    plot(h.pf, border="grey", freq = TRUE, add=TRUE)
  # Plot main histogram
  plot(h, freq = TRUE, add=TRUE)
  if (!is.null(gm)) {
    # Plot model
    p <- diff(ifelse(h$breaks > 0,
                     pgwpcrpois(pmax(h$breaks - 1, 0), threshold=0,
                                molecules=gm$molecules,
                                efficiency=gm$efficiency,
                                lambda0=gm$lambda0) /
                       (1 - gm$p0),
                     0))
    points(h$mids, p * length(readcounts), pch=16, cex=0.7,
           col=ifelse(h$breaks >= ARGS$threshold, 'black', 'red'))
    # Plot Loss
    text(ARGS$threshold/2, par('usr')[4], adj=c(1.0,0.5),
         paste0("Loss=", format(100*gm$loss, digits=2), '%'),
         col='red', srt=90, xpd=TRUE)
    # Plot Model Parameters
    p.txt <- paste0('Efficiency = ', round(100*gm$efficiency), '%\n',
                    'Depth = ', signif(gm$lambda0, digits=2), ' reads/UMI')
    text(par("usr")[2], par("usr")[4], p.txt, adj=c(0.0, 1.0), xpd=NA)
  }
  # Plot Threshold
  lines(c(ARGS$threshold, ARGS$threshold), c(0, par("usr")[4]*2), lwd=2, xpd=TRUE)
  text(ARGS$threshold, par('usr')[4], adj=c(-0.1, 0), xpd=TRUE,
       paste0("Th.=", ARGS$threshold))
  # Plot Legend
  lf <- if (!ARGS$`plot-skip-phantoms`)
    c(TRUE, TRUE, TRUE, TRUE)
  else
    c(TRUE, FALSE, TRUE, TRUE)
  if (!is.null(gm)) {
    legend(par("usr")[2], par("usr")[4] - strheight(p.txt), xjust=0.0, yjust=1.0, seg.len=0,
           pch=c(NA,NA,16,16)[lf], col=c(NA,'darkgrey','black','red')[lf],
           border=c("black","darkgrey",NA,NA)[lf], fill=c(NA,NA,NA,NA)[lf],
           legend=c("Putative true UMIs", "Putative phantom UMIs", "Predicted True UMIs", "Predicted Loss")[lf],
           bty='n', xpd=NA)
  } else {
    legend(par("usr")[2], par("usr")[4], xjust=0.0, yjust=1.0, seg.len=0,
           pch=c(NA,NA,16,16)[lf], col=c(NA,'darkgrey','black','red')[lf],
           border=c("black","darkgrey",NA,NA)[lf], fill=c(NA,NA,NA,NA)[lf],
           legend=c("Putative true UMIs", "Putative phantom UMIs")[lf],
           bty='n', xpd=NA)
  }
  # Plot X-Axis
  bin.l <- head(h.breaks, n=-1)
  bin.r <- tail(h.breaks, n=-1)
  if (x.bin > 1) {
    at=(bin.l+bin.r)/2
    labels=paste0(bin.l, '-', bin.r-1)
    # If we'd need more than 30 labels, leave some out
    indices=seq(from=1, to=length(at), by=ceiling(length(at)/30))
    labels.filtered=rep("", length(at))
    labels.filtered[indices] = labels[indices]
    axis(side=1, line=0, pos=0, at=at, labels=labels.filtered, las=3)
  }
  else
    axis(side=1, line=0, pos=0, at=bin.l+0.5, labels=as.character(bin.l))
  mtext(side=1, line=4, 'x (Reads)')
  # Plot Y-Axis
  axis(side=2, line=0, at=c(0, y.max), labels=c("0", format(y.max, scientific=TRUE)))
  mtext(side=2, line=2, '#UMIs with')
  mtext(side=2, line=1, 'x reads')
}

# ******************************************************************************
# *** Exit early if group-wise fits are not asked for or fitting failed ********
# ******************************************************************************
if (ARGS$`skip-groupwise-fits` || is.null(gm)) {
  quit(save="no", status=0, runLast=TRUE)
}

# ******************************************************************************
# *** Fit group-wise models ****************************************************
# ******************************************************************************
message('*** Fitting group-wise models on ', ARGS$cores, ' cores')
gsm <- gwpcrpois.groupest(group.expr, data=umis, loss=loss.expr,
                          threshold=ARGS$threshold, molecules=ARGS$molecules,
                          ctrl=list(cores=ARGS$cores, verbose=ARGS$`verbose`,
                                    var.est.distfree=ARGS$`var-est-distfree`,
                                    obs.min.ingroup=ARGS$`groupwise-min-umis`,
                                    maxit=2000))
if (!is.null(ARGS$`output-groupwise-fits`)) {
  message('*** Writing groupwise model details to ', ARGS$`output-groupwise-fits`)
  f <- open_byext(ARGS$`output-groupwise-fits`, open='w')
  write.table(gsm, file=f, col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
  close(f)
}
cols <- eval(parse(text=paste0("quote(list(", paste(ARGS$`group-per`, collapse=", "), ", ",
                               "n.umis, n.tot, efficiency, depth=lambda0, loss, n.obs))")))
umicounts <- gsm[, eval(cols)]

# ******************************************************************************
# *** Add pre-filtering and filtered read and UMI counts ***********************
# ******************************************************************************
if (ARGS$`include-filter-statistics`) {
  statspergroup <- umis[
    , n.reads := sum(eval(reads.expr))
    , keyby=eval(ARGS$`group-per`) ]
  statspergroup.prefilter <- umis.prefilter[
    , c("n.umis", "n.reads") := list(length(eval(reads.expr)), sum(eval(reads.expr)))
    , keyby=eval(ARGS$`group-per`) ]
  umicounts[statspergroup, n.reads := statspergroup[, n.reads] ]
  umicounts[statspergroup.prefilter, n.umis.prefilter := statspergroup.prefilter[, n.umis] ]
  umicounts[statspergroup.prefilter, n.reads.prefilter := statspergroup.prefilter[, n.reads] ]
}

# ******************************************************************************
# *** Plot loss estimate variances over number of observations  ****************
# ******************************************************************************
if (!is.null(ARGS$`output-plots`)) {
  # Split d into plot-var-bins bins with similar n.obs, for n.obs > 1
  gsmp <-  gsm[order(n.obs), ][n.obs > 1,]
  gsmp[is.finite(loss.raw)
       , bin := floor(seq(from=1, to=(1-.Machine$double.neg.eps)*ARGS$`plot-var-bins`,
                          length.out=.N)) ]
  # Compute loss variance within bins
  gsm.bin <- gsmp[is.finite(bin)
                  , list(n.obs=mean(n.obs, na.rm=TRUE),
                         loss.raw.var=var(loss.raw, na.rm=TRUE))
                  , by=bin]
  # Extract between-group variance s and baseline estimator error u
  u <- gsm[1, loss.raw.var * n.obs]
  s <- gsm[1, loss.grp.var]
  # Setup plot
  par(mar=c(4.1,4.1,1.1,2.5/par("csi")))
  plot.new()
  xlim=range(c(1, gsm.bin$n.obs))
  plot.window(xlim=xlim,
              ylim=range(c(gsm.bin$loss.raw.var, s+u/2,
                           ifelse(ARGS$`plot-var-logy`, NA, 0)),
                         na.rm=TRUE),
              log=ifelse(ARGS$`plot-var-logy`, 'xy', 'x'))
  axis(side=1)
  axis(side=2)
  title(xlab=ifelse(ARGS$`strand-umis`,
                    "# Strand UMIs / Gene",
                    "# UMIs / Gene"),
        ylab=expression("Total Variance of Loss Estimates"))
  legend(10^par("usr")[2], ifelse(ARGS$`plot-var-logy`, 10^par("usr")[4], par("usr")[4]),
         xjust=0.0, yjust=1.0, xpd=NA,
         lty=c(NA, 2), pch=c(4, NA), c('Empirical', 'Prediction s + u/n'), bty='n')
  # Plot bin-wise empirical loss variance
  gsm.bin[, points(n.obs, loss.raw.var, pch=4) ]
  # Plot prediction
  x <- seq(from=xlim[1], to=xlim[2], length.out=1000)
  lines(x, s + u/x, lty=2)
}

# ******************************************************************************
# *** Output count table *******************************************************
# ******************************************************************************
if (!is.null(ARGS$`output-counts`)) {
  message('*** Writing corrected UMI groupwise counts to ', ARGS$`output-counts`)
  f <- open_byext(ARGS$`output-counts`, open='w')
  write.table(format_table(umicounts, digits=ARGS$digits), file=f,
              col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
  close(f)
}
