#!/bin/bash
../trumicount --help 2>&1 \
	| sed -n 's/^\(--[^ ]*\) \([A-Z]*\) *\(.*\)$/\\item[\\textmd{\\texttt{\1} \2}:] \3/p' \
	| sed 's/_/\\_/g' \
	| sed 's/--/-{}-/g' \
	| sed 's/\([A-Z]\{4,\}\)\($\|[^a-zA-Z]\)/\\textit{\L\1}\2/g' \
	| sed 's/`\([^`]*\)`/\\guillemotleft\\texttt{\1}\\guillemotright{}/g' \
	| sed 's/\[Default: *\([0-9-][0-9]*\)\]/(Default: \\textrm{\1})/' \
	| sed 's/\[Default: \\textit{false}\]/(Default: No)/' \
	| sed 's/\[Default: \\textit{true}\]/(Default: Yes)/' \
	| sed 's/\[Default: *\([^]]*\)\]/(Default: \\textrm{`\1'"'"'})/' \
	> reference.tex
