#!/bin/bash
../trumicount --help 2>&1 \
        | awk 'BEGIN{o=0;c=0;p=""} /^Options:/ {o=1} o==0 {} /^--/ {print p;p=$0} /^ / {sub(/^ */," ",$0);p=p $0} END {print p}' \
	| sed -n 's/^\(--[^ ]*\) \([A-Z0-9,.]*\) *\(.*\)$/\\item[\\textmd{\1 \2}:] \3/p' \
	| sed 's/_/\\_/g' \
	| sed 's/\(--[a-z0-9-]*\)/\\texttt{\1}/g' \
	| sed 's/--/-{}-/g' \
	| sed 's/\([A-Z][A-Z0-9]\{3,\}\)\($\|[^a-zA-Z]\)/\\textit{\L\1}\2/g' \
	| sed 's/`\([^`]*\)`/\\guillemotleft\\texttt{\1}\\guillemotright{}/g' \
	| sed 's/\[Default: *\([0-9-][0-9]*\)\]/(Default: \\textrm{\1})/' \
	| sed 's/\[Default: \\textit{false}\]/(Default: No)/' \
	| sed 's/\[Default: \\textit{true}\]/(Default: Yes)/' \
	| sed 's/\[Default: *\([^]]*\)\]/(Default: \\textrm{`\1'"'"'})/' \
	> reference.tex
